import { Router } from 'express';
import { prisma } from '../index.js';

const router = Router();

// GET /api/customers - Get all customers
router.get('/', async (req, res) => {
  try {
    console.log('📝 Fetching all customers...');
    const customers = await prisma.customer.findMany({
      orderBy: { createdAt: 'desc' },
    });
    console.log(`✅ Found ${customers.length} customers`);
    res.json(customers);
  } catch (error: any) {
    console.error('❌ Failed to fetch customers:', error);
    console.error('Error details:', {
      message: error.message,
      code: error.code,
      meta: error.meta
    });
    res.status(500).json({ 
      error: 'Failed to fetch customers', 
      details: error.message,
      code: error.code 
    });
  }
});

// GET /api/customers/:id - Get customer by ID
router.get('/:id', async (req, res) => {
  try {
    const customer = await prisma.customer.findUnique({
      where: { id: req.params.id },
    });
    if (!customer) {
      return res.status(404).json({ error: 'Customer not found' });
    }
    res.json(customer);
  } catch (error) {
    res.status(500).json({ error: 'Failed to fetch customer' });
  }
});

// POST /api/customers - Create customer
router.post('/', async (req, res) => {
  try {
    console.log('📝 Creating customer with data:', JSON.stringify(req.body, null, 2));
    
    // Remove fields that shouldn't be sent (auto-generated by Prisma or not in schema)
    const { tags, id, createdAt, updatedAt, ...customerData } = req.body;
    
    // Ensure joinDate is a Date object
    if (customerData.joinDate) {
      customerData.joinDate = new Date(customerData.joinDate);
    }
    
    const customer = await prisma.customer.create({
      data: customerData,
    });
    console.log('✅ Customer created successfully:', customer.id);
    res.status(201).json(customer);
  } catch (error: any) {
    console.error('❌ Failed to create customer:', error);
    console.error('Error details:', {
      message: error.message,
      code: error.code,
      meta: error.meta
    });
    res.status(500).json({ error: 'Failed to create customer', details: error.message });
  }
});

// PUT /api/customers/:id - Update customer
router.put('/:id', async (req, res) => {
  try {
    const customer = await prisma.customer.update({
      where: { id: req.params.id },
      data: req.body,
    });
    res.json(customer);
  } catch (error: any) {
    if (error.code === 'P2025') {
      return res.status(404).json({ error: 'Customer not found' });
    }
    res.status(500).json({ error: 'Failed to update customer' });
  }
});

// DELETE /api/customers/:id - Delete customer
router.delete('/:id', async (req, res) => {
  try {
    await prisma.customer.delete({
      where: { id: req.params.id },
    });
    res.status(204).send();
  } catch (error: any) {
    if (error.code === 'P2025') {
      return res.status(404).json({ error: 'Customer not found' });
    }
    res.status(500).json({ error: 'Failed to delete customer' });
  }
});

export { router as customersRouter };

